@startuml

title __DTO's Class Diagram__\n

  namespace com.example {
    namespace model.dto {
      class com.example.model.dto.DetailedOrderDTO {
          - orderState : int
          + DetailedOrderDTO()
          + DetailedOrderDTO()
          + equals()
          + getAcceptedUser()
          + getHostUser()
          + getOrderState()
          + getOrders()
          + getTransOrder()
          + hashCode()
          + setAcceptedUser()
          + setHostUser()
          + setOrderState()
          + setOrders()
          + setTransOrder()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.example {
    namespace model.dto {
      class com.example.model.dto.TransHistoryDTO {
          - nickName : String
          - order_money : double
          - picUrl : String
          - time : String
          + TransHistoryDTO()
          + TransHistoryDTO()
          + equals()
          + getNickName()
          + getOrder_money()
          + getPicUrl()
          + getTime()
          + hashCode()
          + setNickName()
          + setOrder_money()
          + setPicUrl()
          + setTime()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.example {
    namespace model.dto {
      class com.example.model.dto.UpdateOrderDTO {
          - orderId : String
          + UpdateOrderDTO()
          + UpdateOrderDTO()
          + equals()
          + getOrderId()
          + getOrders_ori()
          + getOrders_update()
          + hashCode()
          + setOrderId()
          + setOrders_ori()
          + setOrders_update()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.example {
    namespace model.dto {
      class com.example.model.dto.UserDTO {
          - token : String
          + UserDTO()
          + UserDTO()
          + equals()
          + getToken()
          + getUser()
          + hashCode()
          + setToken()
          + setUser()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.example {
    namespace model.dto {
      class com.example.model.dto.UserTransOrderDTO {
          + UserTransOrderDTO()
          + UserTransOrderDTO()
          + equals()
          + getOpposeUser()
          + getOrders()
          + getTransOrder()
          + hashCode()
          + setOpposeUser()
          + setOrders()
          + setTransOrder()
          + toString()
          # canEqual()
      }
    }
  }
  

  com.example.model.dto.DetailedOrderDTO o-- com.example.model.domain.User : acceptedUser
  com.example.model.dto.DetailedOrderDTO o-- com.example.model.domain.User : hostUser
  com.example.model.dto.DetailedOrderDTO o-- com.example.model.domain.Orders : orders
  com.example.model.dto.DetailedOrderDTO o-- com.example.model.domain.TransOrder : transOrder
  com.example.model.dto.UpdateOrderDTO .up.|> java.io.Serializable
  com.example.model.dto.UpdateOrderDTO o-- com.example.model.domain.Orders : orders_ori
  com.example.model.dto.UpdateOrderDTO o-- com.example.model.domain.Orders : orders_update
  com.example.model.dto.UserDTO o-- com.example.model.domain.User : user
  com.example.model.dto.UserTransOrderDTO o-- com.example.model.domain.User : opposeUser
  com.example.model.dto.UserTransOrderDTO o-- com.example.model.domain.Orders : orders
  com.example.model.dto.UserTransOrderDTO o-- com.example.model.domain.TransOrder : transOrder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
