@startuml

title __UTILS's Class Diagram__\n

  namespace com.example {
    namespace utils {
      class com.example.utils.BitmapUtil {
          {static} - PHOTO_FILE_NAME : String
          {static} + calculateInSampleSize()
          {static} + compressImage()
          {static} + createCircleImage()
          {static} + getRotateAngle()
          {static} + getSmallBitmap()
          {static} + setRotateAngle()
      }
    }
  }
  

  namespace com.example {
    namespace utils {
      class com.example.utils.ChangeTabColor {
          {static} + setStatusBarColor()
      }
    }
  }
  

  namespace com.example {
    namespace utils {
      class com.example.utils.MD5Util {
          {static} + parseStrToMd5L16()
          {static} + parseStrToMd5L32()
          {static} + parseStrToMd5U16()
          {static} + parseStrToMd5U32()
      }
    }
  }
  

  namespace com.example {
    namespace utils {
      class com.example.utils.ScreenUtil {
          {static} + getActionBarHeight()
          {static} + getScreenHeight()
          {static} + getScreenWidth()
          {static} + getStatusBarHeight()
      }
    }
  }
  

  namespace com.example {
    namespace utils {
      class com.example.utils.SharedPreferencesUtil {
          {static} - PASSWORD : String
          {static} - sp : SharedPreferences
          {static} + clear()
          {static} + getBoolean()
          {static} + getInt()
          {static} + getList()
          {static} + getLong()
          {static} + getMap()
          {static} + getObject()
          {static} + getString()
          {static} + getString()
          {static} + putBoolean()
          {static} + putInt()
          {static} + putList()
          {static} + putLong()
          {static} + putMap()
          {static} + putObject()
          {static} + putPassword()
          {static} + putString()
          {static} - get()
          {static} - getSp()
          {static} - put()
      }
    }
  }
  

  namespace com.example {
    namespace utils {
      class com.example.utils.TimeUtil {
          {static} + getCurrentTime()
      }
    }
  }
  

  namespace com.example {
    namespace utils {
      class com.example.utils.UploadUtil {
          {static} + filesToMultipartBodyParts()
          {static} + uploadImage()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
