@startuml

title __CONFIG's Class Diagram__\n

  namespace com.example {
    namespace http {
      namespace config {
        class com.example.http.config.HttpConfig {
            {static} + BASE_URL : String
            {static} + HTTP_TIME : int
        }
      }
    }
  }
  

  namespace com.example {
    namespace http {
      namespace config {
        interface com.example.http.config.URLConfig {
            {static} + image_upload_order : String
            {static} + main_carousel : String
            {static} + main_navigate_act : String
            {static} + main_recommend_order : String
            {static} + main_user_get_order : String
            {static} + main_user_get_order_all : String
            {static} + main_user_get_order_all_hot : String
            {static} + user_accept_order : String
            {static} + user_check_token : String
            {static} + user_check_username : String
            {static} + user_create_order : String
            {static} + user_get_order_delete : String
            {static} + user_get_order_detail : String
            {static} + user_get_order_finish : String
            {static} + user_get_order_finish_record : String
            {static} + user_get_order_hot : String
            {static} + user_get_order_trans : String
            {static} + user_get_user : String
            {static} + user_login_name_password : String
            {static} + user_login_qq : String
            {static} + user_register_username : String
            {static} + user_set_order_compelete : String
            {static} + user_update_info : String
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
