@startuml

title __ACTIVITY's Class Diagram__\n

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityAllOrders {
          {static} + PAGE_NUMBER : int
          {static} + TYPE_DEFAULT : int
          {static} + TYPE_HOT : int
          {static} + TYPE_MONEY : int
          {static} - TAG : String
          - context : Context
          - currentPage : int
          - currentStrategy : int
          - hotUpToDown : boolean
          - list : List<Orders>
          - listView : ListView
          - llHot : LinearLayout
          - llPrice : LinearLayout
          - llTime : LinearLayout
          - moneyUpToDown : boolean
          - refreshLayout : RefreshLayout
          - search_text : EditText
          - timeUpToDown : boolean
          + errorHandle()
          + onClick()
          # onCreate()
          - exitActivity()
          - getSortedList()
          - initView()
          - setListView()
          - setListViewDate()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityDetailOrder {
          {static} - TAG : String
          - btn_receive : Button
          - context : Context
          - mSimpleImageBanner : SimpleImageBanner
          - orderId : String
          - toolbar : Toolbar
          - tv_good_address : TextView
          - tv_good_deadline : TextView
          - tv_good_hot : TextView
          - tv_goodbeizhu : TextView
          - tv_goodintro : TextView
          - tv_goodprice : TextView
          - tv_goodtype : TextView
          - tv_hostname : TextView
          - tv_uploadtime : TextView
          + errorHandle()
          + init()
          # onCreate()
          - exitActivity()
          - initData()
          - setViews()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityLogin {
          {static} + APPID : String
          {static} + AUTHORITIES : String
          {static} - TAG : String
          - context : Context
          - loginPhone : ButtonView
          - loginQQ : ImageView
          - loginUserName : ImageView
          - mTencent : Tencent
          - userPhoneNumber : TextView
          + initViews()
          + onActivityResult()
          + onClick()
          + saveUser()
          # onCreate()
          - jumpToCertainActivity()
          - loginByPhone()
          - loginByQQ()
          - loginByUserName()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityLogin.BaseUiListener {
          + onCancel()
          + onComplete()
          + onError()
          + onWarning()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityLoginUserName {
          {static} + TAG : String
          - btnUserLogin : ShadowButton
          - btnUserRegister : ShadowButton
          - context : Context
          - edTextUserName : MaterialEditText
          - edTextUserPassword : MaterialEditText
          - loginContent : String
          - loginIsOk : boolean
          + errorHandle()
          + initViews()
          + onClick()
          # onCreate()
          - jumpToCertainActivity()
          - successHandle()
          - userLogin()
          - userLoginByUserName()
          - userRegister()
          - userRegisterByUserName()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityPersonCheckOrder {
          {static} - TAG : String
          - btn_receive : Button
          - context : Context
          - isReceive : boolean
          - ll_accept_info : LinearLayout
          - mSimpleImageBanner : SimpleImageBanner
          - orderId : String
          - toolbar : Toolbar
          - tv_good_address : TextView
          - tv_good_deadline : TextView
          - tv_good_hostname_accept : TextView
          - tv_good_hot : TextView
          - tv_good_uploadtime_accept : TextView
          - tv_goodbeizhu : TextView
          - tv_goodintro : TextView
          - tv_goodprice : TextView
          - tv_goodtype : TextView
          - tv_hostname : TextView
          - tv_uploadtime : TextView
          + complete()
          + delete()
          + errorHandle()
          + init()
          # onCreate()
          - exitActivity()
          - initData()
          - setViews()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityPersonCredit {
          - linearLayout : LinearLayout
          - mColors : int[]
          - newCreditSesameView : NewCreditSesameView
          + errorHandle()
          + startColorChangeAnim()
          # onCreate()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityPersonHistory {
          - context : Context
          - recyclerView : RecyclerView
          # onCreate()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityPersonInfo {
          - context : Context
          - iv_touxiang : ImageView
          - latitude : Double
          - ll_location : LinearLayout
          - locationManager : LocationManager
          - longitude : Double
          - toolbar : Toolbar
          - tv_location : TextView
          - tv_nickName : TextView
          - tv_sex : TextView
          + errorHandle()
          + initView()
          + onLocationChanged()
          + onProviderDisabled()
          + onProviderEnabled()
          + onStatusChanged()
          + updateUser()
          # onCreate()
          - exitActivity()
          - getLocation()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityPersonLaunch {
          {static} + PERSON_ACCEPT : int
          {static} + PERSON_ALL : int
          {static} + PERSON_FINISH : int
          {static} + PERSON_LAUNCH : int
          {static} + PERSON_TRANS : int
          - adapter : ListAdapter
          - context : Context
          - currentRequest : int
          - list : List<Orders>
          - listView : ListView
          - search_text : EditText
          + errorHandle()
          + initView()
          # onCreate()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityPersonWallet {
          - tv_mywallet : TextView
          + errorHandle()
          # onCreate()
          - initdb()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityTransHistory {
          - context : Context
          - list : List<TransHistoryDTO>
          - lv_money : ListView
          - nickname : String
          - sharedPreferences : SharedPreferences
          - toolbar : Toolbar
          - useropenid : String
          + errorHandle()
          # onCreate()
          - initdb()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityTransNumber {
          # onCreate()
      }
    }
  }
  

  namespace com.example {
    namespace activity {
      class com.example.activity.ActivityWelcome {
          {static} - TAG : String
          - context : Context
          - handler : Handler
          - isLogined : boolean
          # onCreate()
      }
    }
  }
  

  com.example.activity.ActivityAllOrders .up.|> android.view.View.OnClickListener
  com.example.activity.ActivityAllOrders -up-|> com.example.common.BaseActivity
  com.example.activity.ActivityAllOrders o-- com.example.adapter.OrderListAdapter : adapter
  com.example.activity.ActivityDetailOrder -up-|> com.example.common.BaseActivity
  com.example.activity.ActivityDetailOrder o-- com.example.model.dto.DetailedOrderDTO : detailedOrderDTO
  com.example.activity.ActivityLogin .up.|> android.view.View.OnClickListener
  com.example.activity.ActivityLogin -up-|> com.example.common.BaseActivity
  com.example.activity.ActivityLogin o-- com.example.activity.ActivityLogin.BaseUiListener : mloginlistener
  com.example.activity.ActivityLogin +-down- com.example.activity.ActivityLogin.BaseUiListener
  com.example.activity.ActivityLogin.BaseUiListener .up.|> com.tencent.tauth.IUiListener
  com.example.activity.ActivityLoginUserName .up.|> android.view.View.OnClickListener
  com.example.activity.ActivityLoginUserName -up-|> com.example.common.BaseActivity
  com.example.activity.ActivityPersonCheckOrder -up-|> com.example.common.BaseActivity
  com.example.activity.ActivityPersonCheckOrder o-- com.example.model.domain.User : currentUser
  com.example.activity.ActivityPersonCheckOrder o-- com.example.model.dto.DetailedOrderDTO : detailedOrderDTO
  com.example.activity.ActivityPersonCredit -up-|> com.example.common.BaseActivity
  com.example.activity.ActivityPersonHistory -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.activity.ActivityPersonHistory o-- com.example.adapter.HistoryItemAdapter : itemAdapter
  com.example.activity.ActivityPersonInfo .up.|> android.location.LocationListener
  com.example.activity.ActivityPersonInfo -up-|> com.example.common.BaseActivity
  com.example.activity.ActivityPersonLaunch -up-|> com.example.common.BaseActivity
  com.example.activity.ActivityPersonLaunch o-- com.example.model.domain.User : user
  com.example.activity.ActivityPersonWallet -up-|> com.example.common.BaseActivity
  com.example.activity.ActivityTransHistory -up-|> com.example.common.BaseActivity
  com.example.activity.ActivityTransNumber -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.activity.ActivityWelcome -up-|> com.example.common.BaseActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
